apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: student-backend

  template:
    metadata:
      labels:
        app: student-backend

    spec:
      containers:
        - name: backend
          image: agnik007/devops-pbl3-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: JWT_SECRET
              value: "supersecret"

            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/student_management"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 15